// generated by stringer -type=DeviceState; DO NOT EDIT

package adb

import "fmt"

const _DeviceState_name = "StateDisconnectedStateOfflineStateOnline"

var _DeviceState_index = [...]uint8{0, 17, 29, 40}

func (i DeviceState) String() string {
	if i < 0 || i+1 >= DeviceState(len(_DeviceState_index)) {
		return fmt.Sprintf("DeviceState(%d)", i)
	}
	return _DeviceState_name[_DeviceState_index[i]:_DeviceState_index[i+1]]
}
