// generated by stringer -type=deviceDescriptorType; DO NOT EDIT

package goadb

import "fmt"

const _deviceDescriptorType_name = "DeviceAnyDeviceSerialDeviceUsbDeviceLocal"

var _deviceDescriptorType_index = [...]uint8{0, 9, 21, 30, 41}

func (i deviceDescriptorType) String() string {
	if i < 0 || i+1 >= deviceDescriptorType(len(_deviceDescriptorType_index)) {
		return fmt.Sprintf("deviceDescriptorType(%d)", i)
	}
	return _deviceDescriptorType_name[_deviceDescriptorType_index[i]:_deviceDescriptorType_index[i+1]]
}
