// generated by stringer -type=ErrCode; DO NOT EDIT

package util

import "fmt"

const _ErrCode_name = "AssertionErrorParseErrorServerNotAvailableNetworkErrorConnectionResetErrorAdbErrorDeviceNotFoundFileNoExistError"

var _ErrCode_index = [...]uint8{0, 14, 24, 42, 54, 74, 82, 96, 112}

func (i ErrCode) String() string {
	if i+1 >= ErrCode(len(_ErrCode_index)) {
		return fmt.Sprintf("ErrCode(%d)", i)
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
